---
title: "scratch paper - new data"
author: "An Bui"
date: "10/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(here)
library(vegan)
library(MASS)
library(conflicted)
conflict_prefer("select", "dplyr")
library(ggvegan)
```

```{r data}
birds <- read_csv(here("data", "birds.csv")) %>% 
  rename(point = X1)

birds$point <- paste("point", birds$point, sep = "_")

birds_df <- birds %>% 
  column_to_rownames("point")

trees <- read_csv(here("data", "trees.csv")) %>% 
  rename(point = X1)

trees$point <- paste("point", trees$point, sep = "_")

veg <- read_csv(here("data", "field-veg.csv")) %>%
  rename(point = X1) %>% 
  mutate(ELT = recode(ELT, do = "dry", dm = "mix", wm = "riparian"))

veg$point <- paste("point", veg$point, sep = "_")
```

```{r combine-frames}
indicator_trees <- trees %>% 
  # select desired columns - matches("a|b|c") will give all columns that contain a, b, or c!!!
  select(point, matches("Quercus|Smilax|Vaccinium"), Acer_rubrum, Lindera_benzoin, Acer_saccharum, Ulmus_rubra, Fraxinus_pennsylvanica, Rosa_multiflora, Toxicodendron_radicans, Betula_nigra, Acer_saccharinum)

env <- full_join(veg, indicator_trees, by = "point") %>% 
  select(point, ELT, 2:5, 7:23)

site_type <- env %>% 
  select(point, ELT)
```

```{r write-new-frames}
write_csv(birds, here("data", "bird-comm.csv"))
write_csv(env, here("data", "environmental-variables.csv"))
```

```{r the-data}
# bird communities
birds <- read_csv(here("data", "bird-comm.csv"))

birds_df <- birds %>% 
  column_to_rownames("point")

# environmental variables
env <- read_csv(here("data", "environmental-variables.csv"))

# set up site type df
site_type <- env %>% 
  select(point, ELT)
```

```{r species-accumulation-curve}
bird_sa_curve <- specaccum(birds_df, method = "random", permutations = 200)
df <- data.frame(bird_sa_curve$sites, bird_sa_curve$richness) %>%
  rename(sites = bird_sa_curve.sites,
         richness = bird_sa_curve.richness)

sa_curve <- ggplot(df, aes(x = sites, y = richness)) +
  geom_point()
sa_curve
```

```{r species-rarefaction-curve}
raremax <- min(rowSums(birds_df))

rarecurve(birds_df, step = 20, sample = raremax, label = TRUE)
```

```{r}
boxplot(specnumber(birds_df) ~ site_type$ELT, ylab = "# of species")

bird_aov <- aov(specnumber(birds_df) ~ site_type$ELT)
summary(bird_aov)
```


```{r diversity-indices}
shannondiv <- birds_df %>% 
  diversity() %>% 
  enframe() %>% 
  dplyr::rename(point = name,
                shan_div = value) %>% 
  full_join(site_type, ., by = "point")
shannondiv

shandivplot <- ggplot(shannondiv, aes(x = point, y = shan_div, fill = point)) +
  geom_col(color = "black") +
  theme(legend.position = "none")
shandivplot

shandiv_sum <- shannondiv %>% 
  group_by(ELT) %>% 
  summarize(mean = mean(shan_div),
            err = sd(shan_div)/sqrt(length(shan_div)))

shandiv_sum_plot <- ggplot(shandiv_sum, aes(x = ELT, y = mean, fill = ELT)) +
  geom_col(color = "black") +
  geom_errorbar(aes(ymin = mean - err, ymax = mean + err))
shandiv_sum_plot
```

```{r NMDS}
NMDS <- metaMDS(birds_df, distance = "bray", k = 2, zerodist = "add", trymax = 100)

NMDS

# points: sample scores
# dims: number of NMS axes
# stress: stress of final solutions
# data: what was ordinated and any transformations
# distance: distance metric used
# converged: whether or not solution converged
# tries: number of configurations tried
# species: scores of variables
# call: how function was called

stressplot(NMDS)

plot_df <- as_tibble(NMDS$points) %>% 
  bind_cols(site_type, .)

ggplot(plot_df, aes(x = MDS1, y = MDS2)) +
  geom_point() +
  geom_text(aes(label = point))

ggplot(plot_df, aes(x = MDS1, y = MDS2, color = ELT)) +
  geom_point() +
  stat_ellipse()
```

```{r perMANOVA}
permanova <- adonis(birds_df ~ ELT, data = site_type, method = "bray")
permanova
```

```{r radfit}
rad <- radfit(birds_df[111,])
rad
radlattice(rad)
```

```{r PCA}
PCA <- rda(birds_df)
PCA

biplot(PCA, scaling = -1)
```

```{r RDA}
RDA <- rda(birds_df ~ all_stem_den + big_stem_bas + can_covr_mea, env)
RDA

RDA_coords <- scores(RDA, display = c("sites", "species"))
plot(RDA)
```


```{r CCA}
CCA <- cca(birds_df)
CCA

plot(CCA)
```

```{r CCA-constrained}
CCA_const <- cca(birds_df ~ all_stem_den + can_covr_mea + big_stem_bas + can_heig_mea, data = env)
CCA_const
plot(CCA_const)
```


```{r vegdist}
birds_dist <- vegdist(birds_df) %>% isoMDS(.)
```

```{r rankindex}
rankindex(scale(env), birds_df, c("euc", "man", "bray", "jac", "kul"))
```

```{r envfit}
env_df <- env %>% 
  column_to_rownames("point")

fit <- envfit(NMDS, env_df, permu = 999)
fit

plot(NMDS, display = "sites")
plot(fit, p.max = 0.1)
```

